# Generated by Django 5.1 on 2024-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weeky_exam_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='weekly_exam_photos', verbose_name='')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('creadet_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
