# Generated by Django 5.1 on 2024-12-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeky_exam_photos',
            old_name='creadet_on',
            new_name='created_on',
        ),
    ]
