# Generated by Django 5.1 on 2024-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_creadet_on_weeky_exam_photos_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter_winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Choraklik g'olib",
                'verbose_name_plural': "Choraklik g'oliblar",
            },
        ),
        migrations.AlterModelOptions(
            name='weeky_exam_photos',
            options={'verbose_name': 'Imtihon', 'verbose_name_plural': 'Imtihonlar'},
        ),
    ]
