# Generated by Django 5.1 on 2024-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_quarter_winners_alter_weeky_exam_photos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_winners',
            name='photo',
            field=models.ImageField(upload_to='quarter_winner_photos/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='weeky_exam_photos',
            name='photo',
            field=models.ImageField(upload_to='weekly_exam_photos/%Y/%m/', verbose_name=''),
        ),
    ]
