# Generated by Django 5.1 on 2024-10-01 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('passport', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Passport')),
                ('date_of_bith', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998991234567' formatida kiritilishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('phone2', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998991234567' formatida kiritilishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
