# Generated by Django 5.1 on 2024-08-17 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_bith',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone1',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998991234567' formatida kiritilishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998991234567' formatida kiritilishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
    ]
