# Generated by Django 5.1 on 2024-11-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_status',
            field=models.CharField(blank=True, choices=[('director', 'Direktor'), ('manager', 'Mudir'), ('assistant', 'Kotiba'), ('worker', 'Oddiy hodim'), ('teacher', "O'qtuvchi"), ('assistant_teacher', "Asistent o'qtuvchi"), ('father', 'Ota-ona'), ('student', "O'quvchi")], default='teacher', max_length=30, null=True, verbose_name='Shaxsiy status'),
        ),
    ]
