# Generated by Django 5.1 on 2024-08-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='month',
            field=models.CharField(blank=True, choices=[('january', 'Yanvar'), ('february', 'Fevral'), ('march', 'Mart'), ('april', 'Aprel'), ('may', 'May'), ('june', 'Iyun'), ('july', 'Iyul'), ('august', 'Avgust'), ('september', 'Sentyabr'), ('october', 'Oktyabr'), ('november', 'Noyabr'), ('december', 'Dekabr')], max_length=20, null=True, verbose_name='Oy'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', "To'lanmagan"), ('unfinished', 'Yakunlanmagan'), ('paid', "To'langan")], max_length=30, null=True, verbose_name="To'lov holati"),
        ),
    ]
