# Generated by Django 5.1 on 2024-08-30 15:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_expenses_month_expenses_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='<django.db.models.fields.related.ForeignKey>-payment-<django.db.models.fields.DateTimeField>', unique=True),
        ),
    ]
