# Generated by Django 5.1 on 2024-08-30 15:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='None-payment-<django.db.models.fields.IntegerField>-<django.db.models.fields.CharField>', unique=True),
        ),
    ]
