# Generated by Django 5.1 on 2024-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_expenses_slug_alter_payment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
    ]
