# Generated by Django 5.1 on 2024-12-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('worker', '0003_remove_teacher_salary_remove_worker_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_group', to='worker.teacher', verbose_name='Sinf rahbar'),
        ),
    ]
