# Generated by Django 5.1 on 2024-12-11 09:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='class_name', unique=True),
        ),
    ]
