# Generated by Django 5.1 on 2024-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
