# Generated by Django 5.1 on 2024-12-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
    ]
