# Generated by Django 5.1 on 2024-12-01 07:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Fan nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('photo', models.ImageField(upload_to='science_photos/', verbose_name='Rasm')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Fan haqida')),
                ('is_mainpage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Asosiy sahifa')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
    ]
