# Generated by Django 5.1 on 2024-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='photo',
            field=models.ImageField(upload_to='science_photos/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
