# Generated by Django 5.1 on 2024-08-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maosh')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan')),
                ('is_class_leader', models.BooleanField(default=False, verbose_name='Sinf rahbar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('manager', 'Direktor'), ('little_manager', 'Mudir'), ('assistant', 'Kotiba'), ('worker', 'Oddiy hodim')], default='worker', max_length=100, verbose_name='Lavozim')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Tizimga kirish huquqi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maosh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
