# Generated by Django 5.1 on 2025-12-04 04:42

import django.db.models.deletion
import django.utils.timezone
import worker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('science', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik generatsiya qilinadi.', max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worker.models.teacher_photo_path)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to=worker.models.teacher_passport_path)),
                ('dagree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('is_class_leader', models.BooleanField(default=False)),
                ('is_mainpage', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='science.science')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worker.models.worker_directory_path, verbose_name='Rasm')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Tizimga kirish huquqi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sertifikat nomi.', max_length=250)),
                ('slug', models.SlugField(blank=True, help_text='SEO uchun avtomatik yaratiladigan slug.', max_length=260, null=True, unique=True)),
                ('photo', models.ImageField(help_text='Sertifikatning rasmi.', upload_to=worker.models.teacher_certificate_path)),
                ('status', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(help_text="Qaysi o'qituvchiga tegishli sertifikat.", on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='worker.teacher')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['slug'], name='worker_teac_slug_e53c15_idx'), models.Index(fields=['name'], name='worker_teac_name_4c075f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Teacher_SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram1', 'Telegram 1'), ('telegram2', 'Telegram 2'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('blog1', 'Blog 1'), ('blog2', 'Blog 2')], help_text='Ijtimoiy tarmoq nomi.', max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Tarmoq uchun slug (SEO uchun).', max_length=260, null=True, unique=True)),
                ('url', models.URLField(help_text='Ijtimoiy tarmoq manzili (URL).', max_length=300)),
                ('status', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(help_text="O'qituvchining qaysi ijtimoiy tarmog'i.", on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='worker.teacher')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='worker_teac_name_94b11e_idx'), models.Index(fields=['slug'], name='worker_teac_slug_613162_idx')],
            },
        ),
    ]
