# Generated by Django 5.1 on 2024-12-01 07:45

import autoslug.fields
import django.db.models.deletion
import worker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('science', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=worker.models.slug_funckion_for_teacher, unique=True, verbose_name='slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worker.models.teacher_directory_path, verbose_name='Rasm')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to=worker.models.teacher_directory_path, verbose_name='Rasm')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maosh')),
                ('dagree', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ma'lumoti")),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tajriba(yilda)')),
                ('is_class_leader', models.BooleanField(default=False, verbose_name='Sinf rahbar')),
                ('is_mainpage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Asosiy sahifa')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_science', to='science.science', verbose_name='Fan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sertifikat nomi')),
                ('photo', models.ImageField(upload_to=worker.models.teacher_certificate_directory_path, verbose_name='Rasmi')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_certificate', to='worker.teacher', verbose_name="O'qtuvchi")),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher_SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram1', 'Telegram 1'), ('telegram2', 'Telegram 2'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'You Tube'), ('linkedin', 'LinkedIn'), ('blog1', 'Blog 1'), ('blog2', 'Blog 2')], max_length=50, verbose_name='Nomi')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sm', to='worker.teacher', verbose_name="O'qtuvchi")),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=worker.models.worker_directory_path, verbose_name='Rasm')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Tizimga kirish huquqi')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maosh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
