# Generated by Django 5.1 on 2024-12-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='start_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Ish boshlagan vaqti'),
        ),
    ]
