# Generated by Django 5.1 on 2024-12-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_teacher_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='salary',
        ),
    ]
