# Generated by Django 5.1 on 2024-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Matematika'), ('ict', 'Informatika'), ('english', 'Ingliz tili'), ('russian', 'Rus tili'), ('mather_language', 'Ona tili'), ('history', 'Tarix'), ('sat', 'SAT'), ('pe', 'Jismoniy tarbiya'), ('geography', 'Geografiya'), ('mental', 'Mental arifmetika'), ('biology', 'Biologiya'), ('chemistry', 'Kimyo')], max_length=100, null=True, verbose_name='Fan'),
        ),
    ]
