# Generated by Django 5.1 on 2024-11-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_teacher_personal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='personal_status',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
    ]
