# Generated by Django 5.1 on 2024-11-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_remove_teacher_personal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Sertificat'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dagree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ma'lumoti"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tajriba(yilda)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_mainpage',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Asosiy sahifa'),
        ),
        migrations.CreateModel(
            name='Teacher_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sertifikat nomi')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_certificate', to='worker.teacher', verbose_name="O'qtuvchi")),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher_SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram1', 'Telegram 1'), ('telegram2', 'Telegram 2'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'You Tube'), ('linkedin', 'LinkedIn'), ('blog1', 'Blog 1'), ('blog2', 'Blog 2')], max_length=50, verbose_name='Nomi')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sm', to='worker.teacher', verbose_name="O'qtuvchi")),
            ],
        ),
    ]
