# Generated by Django 5.1 on 2024-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers_photos/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers_photos/', verbose_name='Rasm'),
        ),
    ]
