# Generated by Django 5.1 on 2024-09-11 06:50

import worker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_teacher_photo_worker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=worker.models.teacher_directory_path, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=worker.models.worker_directory_path, verbose_name='Rasm'),
        ),
    ]
