# Generated by Django 5.1 on 2024-12-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_teacher_certificate_slug_teacher_socialmedia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_certificate',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_certificates', to='worker.teacher', verbose_name="O'qtuvchi"),
        ),
        migrations.AlterField(
            model_name='teacher_socialmedia',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sms', to='worker.teacher', verbose_name="O'qtuvchi"),
        ),
    ]
