# Generated by Django 5.1 on 2024-11-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_teacher_certificate_teacher_dagree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='certificate',
        ),
    ]
