# Generated by Django 5.1 on 2024-11-26 16:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_remove_teacher_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='user__first_name', unique=True),
            preserve_default=False,
        ),
    ]
