# Generated by Django 5.1 on 2024-11-26 16:47

import autoslug.fields
import worker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=worker.models.slug_funckion_for_teacher, unique=True, verbose_name='slug'),
        ),
    ]
