# Generated by Django 5.1 on 2024-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='came',
            field=models.BooleanField(default=False, verbose_name='Kelmadi'),
        ),
    ]
