# Generated by Django 5.1 on 2025-12-04 04:42

import django.db.models.deletion
import student.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '__first__'),
        ('science', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=student.models.student_photo_directory_path, verbose_name='Rasm')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirma miqdori')),
                ('student_status', models.CharField(blank=True, choices=[('wanted', "O'qimoqchi bo'lgan"), ('active', "O'qiyotgan"), ('gone_out', 'Chiqib ketgan'), ('expelled', 'Xaydalgan'), ('graduated', 'Bitirgan')], max_length=100, null=True, verbose_name="O'quvchi statusi")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group', verbose_name='Sinf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Father_and_Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Onasining ismi')),
                ('mother_phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Onasining tel 1- raqami')),
                ('mother_phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Onasining tel 2- raqami')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('children', models.ManyToManyField(related_name='parents', to='student.student', verbose_name='Bolalar')),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='Student_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sertifikat nomi')),
                ('photo', models.ImageField(upload_to=student.models.student_certificate_directory_path, verbose_name='Rasm')),
                ('about', models.TextField(verbose_name='Batafsil')),
                ('is_mainpage', models.BooleanField(verbose_name='Asosiy sahifa')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='science.science', verbose_name='Fan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='student.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
