# Generated by Django 5.1 on 2024-08-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirma miqdori')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group', verbose_name='Sinf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Father_and_Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Onasining ismi')),
                ('mother_phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Onasining tel 1- raqami')),
                ('mother_phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Onasining tel 2- raqami')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('children', models.ManyToManyField(related_name='parents', to='student.student', verbose_name='Bolalar')),
            ],
        ),
    ]
