# Generated by Django 5.1 on 2024-12-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_certificate',
            name='is_mainpage',
            field=models.BooleanField(default=1, verbose_name='Asosiy sahifa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_certificate',
            name='science',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='science.science', verbose_name='Fan'),
            preserve_default=False,
        ),
    ]
