# Generated by Django 5.1 on 2024-12-02 12:36

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_certificate_is_mainpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.student_photo_directory_path, verbose_name='Rasm'),
        ),
    ]
