# Generated by Django 5.1 on 2024-11-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_father_and_mother_personal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='father_and_mother',
            name='personal_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal_status',
        ),
    ]
