# Generated by Django 5.1 on 2024-12-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
