# Generated by Django 5.1 on 2024-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('wanted', "O'qimoqchi bo'lgan"), ('active', "O'qiyotgan"), ('gone_out', 'Chiqib ketgan'), ('expelled', 'Xaydalgan'), ('graduated', 'Bitirgan')], max_length=100, null=True, verbose_name="O'quvchi statusi"),
        ),
    ]
