# Generated by Django 5.1 on 2024-12-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='father_and_mother',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
    ]
