# Generated by Django 5.1 on 2024-12-11 18:23

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="E'lon nomi")),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('photo', models.ImageField(upload_to='announcement_photos/%Y/%m/', verbose_name='Rasmi')),
                ('about', models.TextField(verbose_name="E'lon haqida")),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
