# Generated by Django 5.1 on 2025-12-04 04:43

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Graduation_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil nomi')),
                ('number_of_graduates', models.PositiveIntegerField(verbose_name='Bitiruvchilar soni')),
                ('number_of_enrollees', models.PositiveIntegerField(verbose_name="O'qishga kirganlar soni")),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitiruv yili',
                'verbose_name_plural': 'Bitiruv yillari',
            },
        ),
        migrations.CreateModel(
            name='Parents_opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('opinion', models.TextField(verbose_name='Fikr')),
                ('photo', models.ImageField(blank=True, default='D:/projects/my_projects/bm_crm_system/media/default_pictures/person.png', null=True, upload_to='parents_opinion/', verbose_name='Rasm')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ota-onalar fikri',
                'verbose_name_plural': 'Ota-onalar fikrlari',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('university', models.CharField(max_length=250, verbose_name='Universitet nomi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='graduates_photo/%Y/', verbose_name='Rasm')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('graduation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='main_website.graduation_year', verbose_name='Yil')),
            ],
            options={
                'verbose_name': 'Bitiruvchi',
                'verbose_name_plural': 'Bitiruvchilar',
            },
        ),
    ]
