# Generated by Django 5.1 on 2024-12-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
    ]
