# Generated by Django 5.1 on 2024-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Parents_opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('opinion', models.TextField(verbose_name='Fikr')),
                ('photo', models.ImageField(blank=True, default='D:/projects/my_projects/bm_crm_system/media/default_pictures/person.png', null=True, upload_to='parents_opinion/', verbose_name='Rasm')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ota-onalar fikri',
                'verbose_name_plural': 'Ota-onalar fikrlari',
            },
        ),
    ]
