# Generated by Django 5.1 on 2024-12-16 16:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_contact_us_parents_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
