# Generated by Django 5.1 on 2024-12-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_parents_opinion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil nomi')),
                ('number_of_graduates', models.PositiveIntegerField(verbose_name='Bitiruvchilar soni')),
                ('number_of_enrollees', models.PositiveIntegerField(verbose_name="O'qishga kirganlar soni")),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitiruv yili',
                'verbose_name_plural': 'Bitiruv yillari',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('university', models.CharField(max_length=250, verbose_name='Universitet nomi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='graduates_photo/%Y/', verbose_name='Rasm')),
                ('status', models.BooleanField(default=True, verbose_name='Holati')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('graduation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='main_website.graduation_year', verbose_name='Yil')),
            ],
            options={
                'verbose_name': 'Bitiruvchi',
                'verbose_name_plural': 'Bitiruvchilar',
            },
        ),
    ]
