# Generated by Django 5.1 on 2024-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_graduation_year_graduate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
